### ISSUE TITLE
Terminology lags (10 seconds!) on Launch

### ISSUE THREAD

**Issue by lee2sman** [billiob/terminology#62] opened 2020-06-10 22:44 UTC
When I launch Terminology there's about a 10 second lag before the terminal appears, though my default gnome shell launches pretty instantly.

I'm running ```v1.7.0+git30.b02a6d86``` on Ubuntu 18.04LTS with the default GNOME environment, running fish shell. I tested fish and it launches in 0.7seconds.

**Comment by billiob** [comment] 2020-06-11 12:02
One thing you can do to prove the issue is not with fish is to run:
`$ time terminology -e /bin/false` and it will take as much time.
What do you have if you run `$ terminology.efreetd`?
Is it taking as long to run `$ terminology.elementaryConfig`?

**Comment by lee2sman** [comment] 2020-06-11 15:08
Hi,
here's the output of the first

```
Executed in  199.98 millis    fish           external
   usr time   34.16 millis  598.00 micros   33.56 millis
   sys time   26.26 millis  158.00 micros   26.10 millis
```

I don't see any output when I run terminology.efreetd

So when I run elementaryConfig, yes, it takes the same 10 sec lag.

**Comment by billiob** [comment] 2020-06-11 15:14
When running from a terminal `terminology.elementaryConfig`, do you see the same error lines as running `terminology`?
Could you please paste them?

**Comment by lee2sman** [comment] 2020-06-11 15:26
Running these in Terminology, here's the message I get when I run ```terminology.elementaryConfig```:

```
ERR<1449>:efreet_cache ../src/lib/efreet/efreet_cache.c:205 _ipc_launch() Timeout in trying to start '/usr/bin/efreetd' and then connect to efreetd
Resuming activity.
ERR<1449>:edje ../src/lib/edje/edje_util.c:3998 _efl_canvas_layout_efl_layout_calc_calc_size_min() file /snap/terminology/543/usr/share/elementary/themes/default.edj, group elm/toolbar/item/default has a non-fixed part 'elm.swallow.icon'. Adding 'fixed: 1 1;' to source EDC may help. Continuing discarding faulty part.
```

And here's the message I get when I just run ```terminology```:

```
ERR<1664>:efreet_cache lib/efreet/efreet_cache.c:1108 on_send_register() org.enlightenment.DBus.Canceled Canceled by user.
```

**Comment by lee2sman** [comment] 2020-08-07 14:58
Hi, I was able to get this fixed.Terminology was installed twice. I had installed via the ```Ubuntu Software``` app. I was able to uninstall the snap using this app and that fixed things so now when I launch there is no delay!

**Comment by billiob** [comment] 2020-08-07 15:00
Good to know!
Through Ubuntu Software, it could also be the snap version.

**Comment by lee2sman** [comment] 2020-08-07 18:35
just confirmed, it was the snap version, and version v1.8.0+git21.dd3b301d

**Comment by billiob** [comment] 2020-08-10 08:33
Since it seems fixed, I'm closing the issue. Feel free to reopen if needed

**Closed by billiob** 2020-08-10 08:33 UTC

**Comment by fitojb** [comment] 2020-10-30 18:56
The snap should be faster according to https://snapcraft.io/blog/snap-speed-improvements-with-new-compression-algorithm where a less space-efficient but faster compression algorithm was chosen.

**Comment by borisfaure** [comment] 2020-11-04 13:03
Thanks for the heads-up. I hope it will improve things
